import { NextResponse } from "next/server";
import { createId, readCollection, storeFiles, writeCollection } from "@/lib/storage/jsonStore";
import type { Platform, PublishRecord } from "@/types/geo";
import { detectPlatformFromUrl } from "@/types/geo";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Render a minimal HTML page that auto-closes after 2 seconds */
function htmlResult(success: boolean, message: string, detail?: string) {
  const icon = success ? "✅" : "❌";
  const color = success ? "#52c41a" : "#ff4d4f";
  const detailHtml = detail ? `<div style="margin-top:8px;font-size:13px;color:#666">${detail}</div>` : "";
  return new Response(
    `<!DOCTYPE html><html><head><meta charset="utf-8"><title>记录发布</title>
<style>body{font-family:-apple-system,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;background:#f5f5f5}
.card{text-align:center;padding:32px 48px;background:#fff;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.1)}
.icon{font-size:48px;margin-bottom:12px}
.msg{font-size:16px;color:#333}</style></head>
<body><div class="card"><div class="icon">${icon}</div><div class="msg" style="color:${color}">${message}</div>${detailHtml}</div>
<script>setTimeout(()=>window.close(),2000)</script></body></html>`,
    { headers: { "Content-Type": "text/html; charset=utf-8" } },
  );
}

async function quickRecord(publishUrl: string, title?: string) {
  const platform = detectPlatformFromUrl(publishUrl);
  const now = new Date().toISOString();
  const records = await readCollection<PublishRecord>(storeFiles.publishRecords);

  // Try to find an existing draft_synced record for the same platform with a placeholder URL
  const DRAFT_PLACEHOLDER = "草稿箱同步完成，暂无草稿链接";
  const existing = records.find(
    (r) =>
      r.platform === platform &&
      r.syncStatus === "draft_synced" &&
      (r.publishUrl === DRAFT_PLACEHOLDER || !r.publishUrl.startsWith("http")),
  );

  if (existing) {
    // Update the existing record
    existing.publishUrl = publishUrl;
    existing.syncStatus = "published";
    existing.publishedAt = now;
    existing.articleTitle = title || existing.articleTitle;
    existing.note = existing.note ? `${existing.note}；已确认发布` : "已确认发布";
    await writeCollection(storeFiles.publishRecords, records);
    return { updated: true, record: existing };
  }

  // Create a new record (works for any article, including ones not generated by our system)
  const record: PublishRecord = {
    id: createId("publish"),
    contentId: "",
    platform: platform || ("zhihu" as Platform),
    publishUrl,
    articleTitle: title || "",
    publishedAt: now,
    note: "快速记录",
    syncStatus: "manual",
    createdAt: now,
  };

  await writeCollection(storeFiles.publishRecords, [record, ...records]);
  return { updated: false, record };
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const publishUrl = searchParams.get("publishUrl")?.trim();
  const title = searchParams.get("title")?.trim() || undefined;

  if (!publishUrl) {
    return htmlResult(false, "缺少发布链接参数");
  }

  try {
    const result = await quickRecord(publishUrl, title);
    const displayTitle = result.record.articleTitle || title || publishUrl;
    if (result.updated) {
      return htmlResult(true, "已更新发布记录", displayTitle);
    }
    return htmlResult(true, "已记录发布链接", displayTitle);
  } catch (error) {
    return htmlResult(false, `记录失败：${error instanceof Error ? error.message : "未知错误"}`);
  }
}

export async function POST(request: Request) {
  const payload = await request.json() as { publishUrl?: string; title?: string; variantId?: string };

  if (!payload.publishUrl?.trim()) {
    return NextResponse.json({ message: "发布链接不能为空" }, { status: 400 });
  }

  try {
    const result = await quickRecord(payload.publishUrl.trim(), payload.title?.trim() || undefined);
    return NextResponse.json(result, { status: result.updated ? 200 : 201 });
  } catch (error) {
    return NextResponse.json(
      { message: error instanceof Error ? error.message : "记录失败" },
      { status: 500 },
    );
  }
}
